metadata:
  name: explorer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: explorer
  template:
    objectmeta:
      labels:
        app: explorer
    spec:
      containers:
        - name: explorer
          command:
            - yarn
            - workspace
            - '@chainlink/explorer'
            - run
            - prod
          env:
            - name: PGPASSWORD
              value: explorer
            - name: EXPLORER_COOKIE_SECRET
              value: "testingtestingtestingtestingtesting"
            - name: EXPLORER_ADMIN_USERNAME
              value: "admin"
            - name: EXPLORER_ADMIN_PASSWORD
              value: "password"
            - name: TYPEORM_PASSWORD
              value: explorer
            - name: TYPEORM_HOST
              value: 127.0.0.1
            - name: TYPEORM_PORT
              value: 5432
            - name: TYPEORM_DATABASE
              value: explorer_production
            - name: TYPEORM_USERNAME
              value: postgres
            - name: LOG_LEVEL
              value: debug
          image: 'smartcontract/explorer:candidate-0.9.21-rc1'
          ports:
            - containerPort: 8080
            - containerPort: 8081
            - containerPort: 9080
            - containerPort: 9081
          resources:
            requests:
              memory: "1Gi"
              cpu: "2"
            limits:
              memory: "1Gi"
              cpu: "2"
          livenessProbe:
            httpGet:
              path: /metrics
              port: 9080
            initialDelaySeconds: 90
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /metrics
              port: 9080
            initialDelaySeconds: 90
            periodSeconds: 10
        - name: chainlink-explorer-db
          image: postgres:11.6
          ports:
            - containerPort: 5432
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1024m"
          env:
            - name: POSTGRES_DB
              value: explorer_production
              valuefrom: null
            - name: POSTGRES_PASSWORD
              value: explorer
              valuefrom: null
            - name: PGPASSWORD
              value: explorer
              valuefrom: null
            - name: PGUSER
              value: postgres
              valuefrom: null
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
            initialDelaySeconds: 60
            periodSeconds: 60
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
            initialDelaySeconds: 2
            periodSeconds: 2