metadata:
  name: chainlink-explorer-db
spec:
  selector:
    matchLabels:
      app: chainlink-explorer-db
  template:
    objectmeta:
      labels:
        app: chainlink-explorer-db
    spec:
      containers:
        - name: chainlink-explorer-db
          image: postgres:11.6
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: explorer_production
              valuefrom: null
            - name: POSTGRES_PASSWORD
              value: explorer
              valuefrom: null
            - name: PGPASSWORD
              value: explorer
              valuefrom: null
            - name: PGUSER
              value: postgres
              valuefrom: null
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
            initialDelaySeconds: 60
            periodSeconds: 60
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
            initialDelaySeconds: 2
            periodSeconds: 2