objectmeta:
  name: hardhat-network
spec:
  template:
    objectmeta:
      labels:
        app: hardhat-network
    spec:
      containers:
      - name: hardhat-network
        image: smartcontract/hardhat-network
        ports:
        - containerport: {{ .Values.evm.rpcPort }}
        readinessprobe:
          handler:
            exec: null
            httpget:
              path: /
              port:
                intval: {{ .Values.evm.rpcPort }}
          periodseconds: 2
