metadata:
  name: hardhat-network
spec:
  template:
    metadata:
      labels:
        app: hardhat-network
    spec:
      containers:
      - name: hardhat-network
        image: smartcontract/hardhat-network
        ports:
        - containerPort: {{ .Values.evm.rpcPort }}
        readinessProbe:
          httpGet:
            path: /
            port: { { .Values.evm.rpcPort } }
          periodSeconds: 2
